PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://www.openarchives.org/OAI/2.0/oai_dc/>
PREFIX oeaf: <http://licef.ca/oeaf/>

SELECT (count(?s) as ?count)
WHERE '{'
    ?s rdf:type oeaf:cours .
    {0} 

'}'
