PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://www.openarchives.org/OAI/2.0/oai_dc/>
PREFIX mlr-1: <http://standards.iso.org/iso-iec/19788/-1/ed-1/en/>
PREFIX mlr-9: <http://standards.iso.org/iso-iec/19788/-9/ed-1/en/>
PREFIX oeaf: <http://normetic.org/uri/profil_oeaf/v1.0/ns#>

SELECT ?s ?title ?providerName
WHERE '{'
    ?s rdf:type oeaf:rc0002 .
    ?s mlr-1:des0100 ?title .
    ?s oeaf:sed0200 ?provider .
    ?provider mlr-9:des0200 ?providerName .

    {0} 

'}'

OFFSET {1,number,#}
LIMIT {2,number,#}
