PREFIX oeaf: <http://normetic.org/uri/profil_oeaf/v1.0/ns#>
PREFIX mlr-9: <http://standards.iso.org/iso-iec/19788/-9/ed-1/en/>

SELECT ?pubDate ?long ?lat ?descr ?lastMinInfos
WHERE '{'
    OPTIONAL '{'
        ?clo oeaf:sed0400 <{0}> .
        ?clo oeaf:sed1000 ?pubDate
    '}'    
    OPTIONAL '{'
        <{0}> oeaf:sed2000 ?loc
        OPTIONAL '{'
            ?loc mlr-9:des1400 ?long .
        '}'
        OPTIONAL '{'
            ?loc mlr-9:des1500 ?lat .
        '}'
        OPTIONAL '{'
            ?loc mlr-9:des1700 ?descr 
        '}'
    '}'
     OPTIONAL '{'
        <{0}> oeaf:sed3100 ?lastMinInfos
    '}'
'}'
