PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX comete: <http://comete.licef.ca/reference#>

SELECT DISTINCT ?vocUri 
WHERE '{'
    ?s rdf:type comete:VocContext .    
    ?s comete:vocUri ?vocUri .
    '{' ?s comete:vocSourceLocation "{0}" '}'
    UNION
    '{' ?s comete:vocAlias "{0}" '}'    
'}'